## Unit 8 - SQL Case Study, Part 2

In [1]:
# Code for use in each question

import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT *
        FROM Facilities
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db" 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', 5, 25, 10000, 200)
(1, 'Tennis Court 2', 5, 25, 8000, 200)
(2, 'Badminton Court', 0, 15.5, 4000, 50)
(3, 'Table Tennis', 0, 5, 320, 10)
(4, 'Massage Room 1', 9.9, 80, 4000, 3000)
(5, 'Massage Room 2', 9.9, 80, 4000, 3000)
(6, 'Squash Court', 3.5, 17.5, 5000, 80)
(7, 'Snooker Table', 0, 5, 450, 15)
(8, 'Pool Table', 0, 5, 400, 15)

In [2]:
# Question 10
'''
/* Q10: Produce a list of facilities with a total revenue less than 1000.
The output of facility name and total revenue, sorted by revenue. Remember
that there's a different cost for guests and members! */
'''

import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT sq.name, sq.revenue
        FROM (
        SELECT f.name, SUM(CASE WHEN b.memid = 0 THEN b.slots*f.guestcost
                            ELSE b.slots*f.membercost END) AS revenue
        FROM Facilities AS f
            INNER JOIN Bookings as b
                    ON f.facid = b.facid
        GROUP BY f.name) AS sq
        WHERE sq.revenue < 1000
        ORDER BY sq.revenue
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db" 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("Q10: Produce a list of facilities with a total revenue less than 1000.")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
Q10: Produce a list of facilities with a total revenue less than 1000.
('Table Tennis', 180)
('Snooker Table', 240)
('Pool Table', 270)

In [3]:
# Question 11
'''
/* Q11: Produce a report of members and who recommended them in alphabetic surname,firstname order */
'''

import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT m.memid, m.surname, m.firstname, (r.firstname || ' ' || r.surname) AS recommending_member
        FROM Members AS m
            INNER JOIN Members AS r
                    ON m.recommendedby = r.memid
        WHERE m.memid != 0
        ORDER BY m.surname, m.firstname
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db" 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("Q11: Produce a report of members and who recommended them in alphabetic surname,firstname order")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
Q11: Produce a report of members and who recommended them in alphabetic surname,firstname order
(15, 'Bader', 'Florence', 'Ponder Stibbons')
(12, 'Baker', 'Anne', 'Ponder Stibbons')
(16, 'Baker', 'Timothy', 'Jemima Farrell')
(8, 'Boothe', 'Tim', 'Tim Rownam')
(5, 'Butters', 'Gerald', 'Darren Smith')
(22, 'Coplin', 'Joan', 'Timothy Baker')
(36, 'Crumpet', 'Erica', 'Tracy Smith')
(7, 'Dare', 'Nancy', 'Janice Joplette')
(20, 'Genting', 'Matthew', 'Gerald Butters')
(35, 'Hunt', 'John', 'Millicent Purview')
(11, 'Jones', 'David', 'Janice Joplette')
(26, 'Jones', 'Douglas', 'David Jones')
(4, 'Joplette', 'Janice', 'Darren Smith')
(21, 'Mackenzie', 'Anna', 'Darren Smith')
(10, 'Owen', 'Charles', 'Darren Smith')
(17, 'Pinker', 'David', 'Jemima Farrell')
(30, 'Purview', 'Millicent', 'Tracy Smith')
(27, 'Rumney', 'Henrietta', 'Matthew Genting')
(24, 'Sarwin', 'Ramnaresh', 'Florence Bader')
(14, 'Smith', 'Jack', 'Darren Smith')
(9, 'Stibbons', 'Ponder', 'Burton Tracy')
(29, 'Worthington-Smyth', 'Henry', 'Tracy Smith')

In [4]:
# Question 12
'''
/* Q12: Find the facilities with their usage by member, but not guests */
'''

import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT b.facid, f.name, SUM(b.slots) AS member_usage
        FROM Bookings as b
        INNER JOIN Facilities AS f
                ON b.facid = f.facid
        WHERE b.memid != 0
        GROUP BY b.facid
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db" 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("Q12: Find the facilities with their usage by member, but not guests")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
Q12: Find the facilities with their usage by member, but not guests
(0, 'Tennis Court 1', 957)
(1, 'Tennis Court 2', 882)
(2, 'Badminton Court', 1086)
(3, 'Table Tennis', 794)
(4, 'Massage Room 1', 884)
(5, 'Massage Room 2', 54)
(6, 'Squash Court', 418)
(7, 'Snooker Table', 860)
(8, 'Pool Table', 856)

In [5]:
# Question 13
'''
/* Q13: Find the facilities usage by month, but not guests */
'''

import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT b.facid, f.name, strftime('%m', b.starttime) as month, SUM(b.slots) as monthly_usage
        FROM Bookings as b
        INNER JOIN Facilities as f
                ON b.facid = f.facid
        WHERE b.memid != 0
        GROUP BY b.facid, month
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db" 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("Q13: Find the facilities usage by month, but not guests")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
Q13: Find the facilities usage by month, but not guests
(0, 'Tennis Court 1', '07', 201)
(0, 'Tennis Court 1', '08', 339)
(0, 'Tennis Court 1', '09', 417)
(1, 'Tennis Court 2', '07', 123)
(1, 'Tennis Court 2', '08', 345)
(1, 'Tennis Court 2', '09', 414)
(2, 'Badminton Court', '07', 165)
(2, 'Badminton Court', '08', 414)
(2, 'Badminton Court', '09', 507)
(3, 'Table Tennis', '07', 98)
(3, 'Table Tennis', '08', 296)
(3, 'Table Tennis', '09', 400)
(4, 'Massage Room 1', '07', 166)
(4, 'Massage Room 1', '08', 316)
(4, 'Massage Room 1', '09', 402)
(5, 'Massage Room 2', '07', 8)
(5, 'Massage Room 2', '08', 18)
(5, 'Massage Room 2', '09', 28)
(6, 'Squash Court', '07', 50)
(6, 'Squash Court', '08', 184)
(6, 'Squash Court', '09', 184)
(7, 'Snooker Table', '07', 140)
(7, 'Snooker Table', '08', 316)
(7, 'Snooker Table', '09', 404)
(8, 'Pool Table', '07', 110)
(8, 'Pool Table', '08', 303)
(8, 'Pool Table', '09', 443)